
@url = http://localhost:5000/api/v1/category

###Get all category

Get {{url}}?where=level,1

###Get all with children

Get {{url}}/children

###Get by id

Get {{url}}/63d5e169d08aebe295d5e1af

###Get parent id

Get {{url}}/parent/63c7c0ff8015cb65d7433c15

### create category
Post {{url}}
Content-Type: application/json

{
    "name":"Kinh tế con",
    "slug": "Kinh-te-con",
    "level": 2,
    "parentId": "63de297f425226c500ff08fc"
}

### update
Patch {{url}}/63d5e169d08aebe295d5e1af
Content-Type: application/json

{
   "name":"Blockchain1",
    "slug": "block-chain1"
}

###delete

DELETE {{url}}/63c02b529c4b9f9692bb0f0e

###delete vinh vien

DELETE {{url}}/force/63c02b529c4b9f9692bb0f0e