
@url = http://localhost:5000/api/v1/category

###Get all category

Get {{url}}

###Get by id

Get {{url}}/63d5e169d08aebe295d5e1af

###Get parent id

Get {{url}}/parent/63c7c0ff8015cb65d7433c15

### get get-role-id-gte-5
Get {{url}}/get-role-id-gte-5

### create category
Post {{url}}
Content-Type: application/json

{
    "name":"Blockchain3",
    "slug": "block-chain3",
    "level": 2,
    "parentId": "63c7c0ff8015cb65d7433c15"
}

### update
Patch {{url}}/63d5e169d08aebe295d5e1af
Content-Type: application/json

{
   "name":"Blockchain1",
    "slug": "block-chain1"
}

###delete

DELETE {{url}}/63c02b529c4b9f9692bb0f0e

###delete vinh vien

DELETE {{url}}/force/63c02b529c4b9f9692bb0f0e