@url = http://localhost:5000/api/v1/user

###Get all user

GET {{url}}?sort=email,desc&search=thine2&field=email

###Get by id

GET {{url}}/63c108fe653e521d1b789948

###create user

POST {{url}}
Content-Type: application/json

{
    "email":"thine13@gmail.com",
    "password":"thine13"
}

###update user

PATCH {{url}}/63d495b13f4b290a06c17e80
Content-Type: application/json

{
    "email":"thine2@gmail.com",
    "full_name": "thine2"
}

###change password user

PATCH {{url}}/63d495b13f4b290a06c17e80
Content-Type: application/json

{
    "password": "thine2"
}